/* Ackerzeit management UI and locally bundled 3D view. */
(() => {
  'use strict';
  const E=window.Farm,KEY='ackerzeit-save-v1',$=s=>document.querySelector(s),money=n=>n.toLocaleString('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:Number.isInteger(n)?0:2}),num=(n,d=1)=>n.toLocaleString('de-DE',{maximumFractionDigits:d}),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let state=E.fresh(),view='hof',selected=1,action='cultivate',toastTimer,persistenceBlocked=false,stopMap=null;
  let mapGeneration=0;
  const pages=[['hof','▦','Hofübersicht'],['felder','▤','Flächen'],['arbeit','▷','Arbeitsplanung'],['maschinen','▣','Maschinen'],['lager','▥','Lager & Markt'],['finanzen','€','Finanzen']];
  const stageNames={stubble:'Stoppel / unbearbeitet',prepared:'Saatbereit',growing:'Im Wachstum',ready:'Erntereif'};
  const shortDate=d=>new Date(d+'T12:00:00Z').toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',timeZone:'UTC'});
  try{const raw=localStorage.getItem(KEY);if(raw){const saved=JSON.parse(raw);if(!E.validate(saved))throw Error('invalid');state=saved;}}catch{persistenceBlocked=true;$('#save-warning').hidden=false;$('#save-warning').textContent='Der gespeicherte Spielstand konnte nicht geladen werden. Er wird nicht überschrieben. Du spielst vorläufig einen neuen Hof. Exportiere deinen Fortschritt oder lade unter Spielhilfe einen gültigen Spielstand.';}
  function persist(){if(persistenceBlocked)return;try{localStorage.setItem(KEY,JSON.stringify(state));$('#save-status').textContent='Automatisch gespeichert · nur auf diesem Gerät';}catch{$('#save-warning').hidden=false;$('#save-warning').textContent='Automatisches Speichern ist nicht verfügbar. Bitte sichere deinen Fortschritt über Spielhilfe → Spielstand exportieren.';$('#save-status').textContent='Nicht gespeichert – bitte Spielstand exportieren';}}
  function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
  function meter(n){return '<div class="meter"><i style="width:'+Math.max(0,Math.min(100,n))+'%"></i></div>';}
  function badge(f){return '<span class="badge '+(f.stage==='ready'?'amber':f.stage==='prepared'?'blue':'')+'">'+stageNames[f.stage]+'</span>';}
  function title(name,desc,tag=''){return '<div class="section-title"><div><h2>'+name+'</h2><p>'+desc+'</p></div>'+(tag?'<span class="badge">'+tag+'</span>':'')+'</div>';}
  function panel(name,content,extra=''){return '<section class="panel"><div class="panel-head"><h3>'+name+'</h3>'+extra+'</div><div class="panel-body">'+content+'</div></section>';}
  function hint(){const ready=state.fields.find(f=>f.stage==='ready');if(ready)return '<strong>Erntezeit auf '+esc(ready.name)+'.</strong> Plane einen Lohnunternehmer ein. Bei Regen pausiert die Ernte.';if(state.jobs.length)return '<strong>'+state.jobs.length+' Auftrag'+(state.jobs.length>1?'e':'')+' eingeplant.</strong> Mit „Nächster Tag“ werden bis zu 8 Arbeitsstunden ausgeführt. Wetterbedingte Wartezeiten findest du in der Arbeitsplanung.';if(E.month(state)===2||E.month(state)===3)return '<strong>Die Frühjahrssaison beginnt.</strong> Bearbeite deine Felder, säe Sommergerste und dünge den Bestand. Aussaat ist bis Ende April möglich.';if([8,9].includes(E.month(state)))return '<strong>Zeit für Winterweizen.</strong> Bereite abgeerntete Felder vor und säe bis Ende Oktober. Die Ernte folgt im nächsten Sommer.';if([11,0,1].includes(E.month(state)))return '<strong>Winter auf dem Hof.</strong> Warte den Traktor, kaufe Betriebsmittel und plane die nächste Saison.';return '<strong>Behalte deinen Betrieb im Blick.</strong> Wachstum, Bodenfeuchte und Lagerpreise ändern sich im Jahresverlauf.';}
  function fieldsTable(){return '<div class="table-scroll"><table><thead><tr><th>Schlag</th><th>Kultur / Zustand</th><th>Wachstum</th><th>Bodenfeuchte</th><th>Arbeit</th></tr></thead><tbody>'+state.fields.map(f=>'<tr class="'+(f.id===selected?'selected-row':'')+'"><td><strong>'+esc(f.name)+'</strong><small>'+num(f.ha)+' ha · Schlag 0'+f.id+'</small></td><td>'+(f.crop?E.CROPS[f.crop].name:'Keine Kultur')+'<small>'+stageNames[f.stage]+'</small></td><td>'+(f.crop?num(Math.min(100,f.heat/E.CROPS[f.crop].heat*100),0)+' %':'—')+'</td><td>'+num(f.moisture,0)+' %<small>'+(f.moisture>78?'Zu nass':f.moisture<22?'Trocken':'Tragfähig')+'</small></td><td><button data-field="'+f.id+'">'+(E.busy(state,f)?'Auftrag ansehen':'Bewirtschaften')+'</button></td></tr>').join('')+'</tbody></table></div>';}
  function fieldDetail(){const f=state.fields.find(f=>f.id===selected)||state.fields[0];const available=Object.keys(E.ACTIONS).filter(k=>!E.reason(state,f,k));if(!available.includes(action))action=available[0]||'cultivate';const cost=E.estimate(state,f,action),reason=E.reason(state,f,action),weather=E.weatherReason(state,f,action);return panel('Schlag 0'+f.id+' · '+esc(f.name),
    '<div class="kv"><span>Fläche</span><strong>'+num(f.ha)+' ha</strong></div><div class="kv"><span>Zustand</span>'+badge(f)+'</div><div class="kv"><span>Kultur</span><strong>'+(f.crop?E.CROPS[f.crop].name:'Keine')+'</strong></div>'+(f.crop?'<div class="kv"><span>Bestandszustand</span><strong>'+num(f.health,0)+' %</strong></div>'+meter(f.health)+'<div class="kv"><span>Düngung</span><strong>'+(f.fertilized?'Erledigt':'Ausstehend')+'</strong></div><div class="kv"><span>Ertragsschätzung</span><strong>'+num(E.yieldFor(f))+' t</strong></div>':'')+'<div class="kv"><span>Bodenfeuchte</span><strong>'+num(f.moisture,0)+' %</strong></div>'+meter(f.moisture)+(f.lastCrop?'<p class="small muted">Vorfrucht: '+E.CROPS[f.lastCrop].name+'. Gleiche Folgefrucht: −15 % Ertrag.</p>':'')+
    (E.busy(state,f)?'<div class="hint">Hier ist eine Arbeit eingeplant.</div><button data-view="arbeit">Zur Arbeitsplanung</button>':'<div class="action-form"><label for="field-action">Nächste Arbeit</label><select id="field-action">'+Object.entries(E.ACTIONS).map(([key,a])=>'<option value="'+key+'" '+(key===action?'selected':'')+'>'+a.name+'</option>').join('')+'</select><p class="action-note" id="action-note">'+actionInfo(f,action)+'</p><button class="primary" id="queue" '+(reason?'disabled':'')+'>Arbeit einplanen</button></div>'));
  }
  function actionInfo(f,key){const e=E.estimate(state,f,key),why=E.reason(state,f,key);if(why)return esc(why);return num(e.hours)+' h · '+money(e.cost)+' Arbeitskosten · '+num(e.fuel)+' l Diesel'+(e.seed?' · '+num(e.seed,2)+' t Saatgut':'')+(e.fertilizer?' · '+num(e.fertilizer,2)+' t Dünger':'')+'. Kosten und Material werden bei Planung reserviert.'+(E.weatherReason(state,f,key)?' '+E.weatherReason(state,f,key):'');}
  function recent(limit=4){return state.log.slice(0,limit).map(l=>'<div class="event"><time>'+shortDate(l.day)+'</time>'+esc(l.text)+'</div>').join('');}
  function hof(){return '<div class="hof-layout"><section class="panel world-panel"><div class="panel-head"><div><span class="eyebrow">SONNENRAIN · '+E.season(state).toUpperCase()+'</span><h3>Dein Hof in 3D</h3></div><span class="world-tag">FARMALL D-320</span></div><div class="world" id="farm-world"><div class="world-toolbar"><div class="tool-group"><button data-mode="select" aria-pressed="true" class="active">Auswählen</button><button data-mode="drive" aria-pressed="false" disabled>Fahren</button><button data-map="stop" disabled>Stopp</button></div><div class="tool-group"><button data-map="tractor" disabled>Traktor</button><button data-map="home">Hof</button><button data-map="zoom-in" aria-label="Vergrößern">+</button><button data-map="zoom-out" aria-label="Verkleinern">−</button><button data-map="pause" aria-pressed="false">Pause</button></div></div><div class="three-surface"><p class="loading-scene">Dein Hof wird aufgebaut …</p></div><div class="world-status"><span data-three-status role="status">3D-Ansicht wird geladen …</span><strong data-speed>0 km/h</strong></div></div><div class="world-help">Ziehen: Kamera · Zwei Finger: Zoom · Feld antippen: verwalten</div><div class="field-pills">'+state.fields.map(f=>'<button class="field-pill '+(f.id===selected?'selected':'')+'" data-field="'+f.id+'">0'+f.id+' '+esc(f.name)+'</button>').join('')+'</div><div class="world-footnote">Freie Fahrt · Feldarbeiten und Wachstum über „Nächster Tag“</div></section><aside class="hof-detail" id="hof-detail"><button class="detail-close" data-close-field aria-label="Felddetails schließen">Schließen ×</button><div id="hof-field-content">'+fieldDetail()+'</div><div class="hint">'+hint()+'</div>'+panel('Hoftagebuch',recent(3))+'</aside></div>';}
  function pickField(id){
    if(!state.fields.some(f=>f.id===id)){view='felder';location.hash=view;render();return;}
    selected=id;
    if(view==='hof'){
      $('#hof-field-content').innerHTML=fieldDetail();$('#hof-detail').classList.add('is-open');
      document.querySelectorAll('.field-pill').forEach(b=>b.classList.toggle('selected',Number(b.dataset.field)===selected));stopMap?.select?.(id);
    }else render();
  }
  function felder(){return title('Flächen & Anbau','Boden vorbereiten. Kultur wählen. Den richtigen Zeitpunkt treffen.')+'<div class="grid-hof"><div><section class="panel">'+fieldsTable()+'</section>'+panel('Anbaukalender','<div class="table-scroll"><table><thead><tr><th>Kultur</th><th>Aussaat</th><th>Ernte</th></tr></thead><tbody><tr><td>Sommergerste</td><td>März – April</td><td>Juli – September</td></tr><tr><td>Winterweizen</td><td>September – Oktober</td><td>Juli – September im Folgejahr</td></tr></tbody></table></div><p class="small muted">Wärmesumme und Wasser bestimmen die Reife. Düngung steigert den Ertrag. Eine wiederholte Kultur senkt ihn um 15 %. Ungeerntete reife Bestände gehen im Oktober verloren.</p>')+panel('Landangebot · Am Waldrand','<p>2 ha Ackerland direkt am Hof. Kaufpreis: <strong>28.000 €</strong>.</p><button data-do="land" '+(state.fields.length>=4?'disabled':'')+'>'+(state.fields.length>=4?'Bereits gekauft':'Feld kaufen · 28.000 €')+'</button>')+'</div><div>'+fieldDetail()+'</div></div>';}
  function arbeit(){return title('Arbeitsplanung','Du und dein Traktor · 8 Arbeitsstunden pro Tag',state.jobs.length+' AUFTRÄGE')+'<div class="hint">Arbeiten werden in Listenreihenfolge ausgeführt. Bei blockierten Aufträgen wird die nächste mögliche Arbeit erledigt. „Bis zu 7 Tage“ hält bei fertigen Arbeiten, Erntereife und Monatswechsel an.</div><div class="two-col"><div><section class="panel">'+(state.jobs.length?state.jobs.map(j=>{const f=state.fields.find(f=>f.id===j.field),why=E.reason(state,f,j.key,true)||E.weatherReason(state,f,j.key);return '<div class="job-card"><div class="job-card-header"><strong>'+esc(f.name)+'</strong><span class="badge '+(why?'amber':'')+'">'+(why?'WARTET':'GEPLANT')+'</span></div><p>'+E.ACTIONS[j.key].name+'</p>'+meter((1-j.remaining/j.total)*100)+'<div class="kv"><span>Verbleibende Arbeitszeit</span><strong>'+num(j.remaining)+' h</strong></div>'+(why?'<p class="negative">'+esc(why)+'</p>':'')+'<button data-cancel="'+j.id+'">Stornieren</button></div>';}).join(''):'<div class="empty">Keine Arbeiten eingeplant.<br>Wähle ein Feld und plane die nächste Tätigkeit.<p><button data-view="felder">Zu den Flächen</button></p></div>')+'</section>'+panel('Heutiges Wetter','<div class="forecast"><div class="weather-large">'+(state.weather.rain?'☂':'☀')+'</div><div><strong>'+state.weather.temp+' °C</strong><span>'+state.weather.label+' · '+num(state.weather.rain)+' mm Niederschlag</span></div></div><p class="small muted">Bei Frost oder Bodenfeuchte über 78 % pausieren Feldarbeiten. Die Ernte braucht einen regenfreien Tag und höchstens 67 % Bodenfeuchte.</p>')+'</div>'+panel('Hoftagebuch',recent(12))+'</div>';}
  function maschinen(){const cost=Math.ceil((100-state.tractor.condition)*35);return title('Maschinen & Werkstatt','Ein kleiner Maschinenpark für die ersten Wirtschaftsjahre.')+'<div class="two-col">'+panel('McCormick Farmall D-320 · 20 PS','<img class="machine-preview" src="assets/models/farmall-d320.png" alt="Roter Farmall D-320 in 3D"><button data-view="hof">Zum Traktor auf dem Hof</button><div class="kv"><span>Zustand</span><strong>'+num(state.tractor.condition,0)+' %</strong></div>'+meter(state.tractor.condition)+'<div class="kv"><span>Betriebsstunden</span><strong>'+num(state.tractor.hours)+' h</strong></div><div class="kv"><span>Diesel im Hoftank</span><strong>'+num(state.fuel)+' l</strong></div><p class="small muted">Unter 20 % Zustand sind keine eigenen Feldarbeiten möglich. Wartung kostet 35 € pro fehlendem Prozentpunkt und benötigt in dieser Version keinen Spieltag.</p><button data-do="maintain" '+(state.tractor.condition===100||state.jobs.length?'disabled':'')+'>Vollständig warten · '+money(cost)+'</button>'+(state.jobs.length?'<p class="small muted">Wartung erst nach Abschluss oder Stornierung der Feldaufträge.</p>':''))+panel('Anbaugeräte & Ernte','<div class="kv"><strong>Grubber · 2,5 m</strong><span>Im Besitz</span></div><p class="small muted">Bodenbearbeitung · 1,1 h/ha · 13 l/ha</p><div class="kv"><strong>Sämaschine · 3 m</strong><span>Im Besitz</span></div><p class="small muted">Aussaat · 0,65 h/ha · 7 l/ha</p><div class="kv"><strong>Düngerstreuer</strong><span>Im Besitz</span></div><p class="small muted">Düngung · 0,3 h/ha · 3 l/ha</p><div class="kv"><strong>Mähdrescher</strong><span>Lohnunternehmer</span></div><p class="small muted">155 €/ha · 0,45 h/ha. Enthält Fahrer, Maschine und Kraftstoff. Die Ernte belegt für Koordination und Abfuhr ebenfalls deine tägliche Arbeitszeit.</p><button data-view="arbeit">Arbeiten verwalten</button>')+'</div>';}
  function lager(){return title('Lager & Markt','Betriebsmittel einkaufen und deine Ernte vermarkten.')+'<div class="two-col">'+panel('Getreidelager','<div class="kv"><span>Belegung</span><strong>'+num(state.stock.barley+state.stock.wheat)+' / '+state.storage+' t</strong></div>'+meter((state.stock.barley+state.stock.wheat)/state.storage*100)+Object.entries(E.CROPS).map(([k,c])=>'<div class="job-card"><h3>'+c.name+'</h3><div class="kv"><span>'+num(state.stock[k],2)+' t auf Lager</span><strong>'+money(E.price(state,k))+' / t</strong></div><div class="shop-row"><label><span>Verkauf in Tonnen</span><input id="sell-'+k+'" aria-label="'+c.name+' Verkaufsmenge in Tonnen" type="number" min="0.01" max="'+state.stock[k]+'" step="0.01" value="'+state.stock[k]+'"></label><button data-sell="'+k+'" '+(!state.stock[k]?'disabled':'')+'>Verkaufen</button></div></div>').join('')+'<p class="small muted">Preise schwanken saisonal. Verkaufserlöse werden sofort gutgeschrieben.</p><button data-do="expand" '+(state.storage>=200?'disabled':'')+'>Lager +40 t · 6.500 €</button>')+panel('Betriebsmittel','<p class="small muted">Bei der Arbeitsplanung reserviertes Material ist bereits vom Bestand abgezogen.</p>'+Object.entries(E.SHOP).map(([k,p])=>'<div class="job-card"><h3>'+p.name+'</h3><div class="kv"><span>'+num(E.stockOf(state,k),2)+' / '+p.cap+' '+p.unit+' verfügbar</span><strong>'+money(p.price)+' / '+p.unit+'</strong></div><div class="shop-row"><label><span>Kaufmenge in '+p.unit+'</span><input id="buy-'+k+'" aria-label="'+p.name+' Kaufmenge in '+p.unit+'" type="number" min="0.01" step="'+(k==='fuel'?'10':'0.1')+'" value="'+(k==='fuel'?'200':'1')+'"></label><button data-buy="'+k+'">Kaufen</button></div></div>').join(''))+'</div>';}
  function finanzen(){return title('Finanzen','Zahlungsfähigkeit sichern und Wachstum finanzieren.')+'<div class="two-col">'+panel('Betriebsübersicht','<div class="kv"><span>Kontostand</span><strong>'+money(state.cash)+'</strong></div><div class="kv"><span>Offener Kredit</span><strong>'+money(state.debt)+'</strong></div><div class="kv"><span>Einnahmen seit Spielstart</span><strong class="positive">'+money(state.income)+'</strong></div><div class="kv"><span>Ausgaben seit Spielstart</span><strong>'+money(state.expenses)+'</strong></div><div class="kv"><span>Zahlungsüberschuss ohne Kredite</span><strong class="'+(state.income-state.expenses<0?'negative':'positive')+'">'+money(state.income-state.expenses)+'</strong></div><p class="small muted">Hofkosten: 8 € pro Tag. Ausgaben enthalten auch Käufe und reservierte Arbeitskosten. Kreditauszahlungen und Tilgungen zählen nicht als Betriebsergebnis. Alle Werte sind Spielwerte ohne Steuerberechnung.</p>')+panel('Betriebskredit','<p>10.000 € je Auszahlung · maximal 50.000 € Kredit.</p><div class="kv"><span>Zins pro Jahr</span><strong>5 %</strong></div><div class="kv"><span>Aktuelle Zinsen pro Monat</span><strong>'+money(state.debt*0.05/12)+'</strong></div><div class="inline-buttons"><button data-do="loan" '+(state.debt>=50000?'disabled':'')+'>10.000 € aufnehmen</button><button data-do="repay" '+(!state.debt||state.cash<10000?'disabled':'')+'>10.000 € tilgen</button></div><p class="small muted">Zinsen werden am Monatsanfang abgebucht. Bei negativem Kontostand kannst du weiter Zeit verstreichen lassen, aber keine kostenpflichtigen Arbeiten bestellen.</p>')+'</div><section class="panel"><div class="panel-head"><h3>Buchungen</h3><span class="small muted">Letzte 60 Einträge</span></div>'+(state.ledger.length?'<div class="table-scroll"><table><thead><tr><th>Datum</th><th>Buchung</th><th>Betrag</th></tr></thead><tbody>'+state.ledger.slice(0,60).map(l=>'<tr><td>'+shortDate(l.day)+'</td><td>'+esc(l.label)+'</td><td class="'+(l.amount<0?'negative':'positive')+'">'+money(l.amount)+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">Noch keine Buchungen vorhanden.</div>')+'</section>';}
  function hilfe(){return title('Spielhilfe & Spielstand','Alles für dein erstes Jahr auf Sonnenrain.')+'<div class="two-col">'+panel('Dein erstes Wirtschaftsjahr','<p><strong>3D-Hof:</strong> Ziehen verschiebt die Kamera. Im Modus „Fahren“ fährt der Farmall zur angetippten freien Stelle. „Traktor“ zeigt ihn aus der Nähe, „Hof“ die Übersicht. Freie Fahrt verändert keine Bestände und bearbeitet keine Felder. Aufträge, Dieselverbrauch und Wachstum laufen über den Tageswechsel.</p><ol class="help-list"><li>Wähle unter <strong>Flächen</strong> einen Schlag, plane die Bodenbearbeitung und gehe zum nächsten Tag.</li><li>Säe im März oder April <strong>Sommergerste</strong>. Plane nach der Aussaat eine Düngung ein. Beginne so mit allen drei Feldern.</li><li>Lass mit <strong>Bis zu 7 Tage</strong> Zeit verstreichen. Bei wichtigen Ereignissen hält die Zeit an.</li><li>Bestelle im Sommer bei Erntereife den <strong>Lohnunternehmer</strong>. Verkaufe die Ernte unter Lager & Markt.</li><li>Bearbeite die Stoppeln und säe im September oder Oktober <strong>Winterweizen</strong>. Er überwintert und wird im nächsten Sommer geerntet.</li></ol><details><summary>Was beeinflusst den Ertrag?</summary><p>Wärmesumme, Trockenheit, Staunässe, Düngung und Vorfrucht. Reifes Getreide verliert nach 21 Tagen auf dem Feld an Zustand. Die Ertragsschätzung berücksichtigt den aktuellen Zustand; sie kann bis zur Ernte sinken.</p></details><details><summary>Was ist noch vereinfacht?</summary><p>Wetter und Wachstumsmodell sind spielerische Annäherungen an einen mitteleuropäischen Betrieb. Bodenarten, Unkraut, Pflanzenschutz, detaillierte Nährstoffbilanzen, Tierhaltung, Personalverwaltung, Subventionen und Steuern folgen erst später. Die Preise sind Spielwerte, keine aktuellen Marktpreise. Eine stornierte Teilbearbeitung muss erneut geplant werden; ungenutztes Material wird zurückgegeben.</p></details><details><summary>Zeit und Wetter</summary><p>Die angezeigten Wetterwerte gelten für den Tag, der mit „Nächster Tag“ abgearbeitet wird. Danach beginnt der neue Tag. Regen füllt den Bodenwasservorrat; Verdunstung und Drainage trocknen ihn ab. Es läuft keine Zeit, wenn du das Spiel schließt.</p></details>')+panel('Spielstand sichern','<p>Dein Fortschritt wird nach jeder Aktion in diesem Browser gespeichert. Ein anderes Gerät oder Browserprofil hat einen eigenen Spielstand.</p><div class="inline-buttons"><button data-do="export">Spielstand exportieren</button><button data-do="import">Spielstand importieren</button></div><p class="small muted">Sichere deinen Spielstand vor dem Löschen von Browserdaten oder einem Gerätewechsel als JSON-Datei.</p><details><summary>Neuen Betrieb starten</summary><p>Ersetzt den aktuellen Spielstand auf diesem Gerät. Exportiere ihn vorher, wenn du ihn behalten möchtest.</p><button data-do="reset">Neues Spiel starten</button></details>')+'</div>';}
  function render(){
    const generation=++mapGeneration;
    if(stopMap){stopMap();stopMap=null;}
    document.body.dataset.page=view;
    $('#nav').innerHTML=pages.map(([key,icon,name])=>'<button class="nav-button '+(view===key?'active':'')+'" data-view="'+key+'" '+(view===key?'aria-current="page"':'')+'><span class="nav-icon" aria-hidden="true">'+icon+'</span>'+name+'</button>').join('')+'<button class="nav-button '+(view==='hilfe'?'active':'')+'" data-view="hilfe"><span class="nav-icon" aria-hidden="true">?</span>Spielhilfe</button>';
    $('#season-label').textContent=E.season(state)+' · Wirtschaftsjahr '+(E.date(state).getUTCFullYear()-2025);
    $('#date-label').textContent=E.date(state).toLocaleDateString('de-DE',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
    $('#calendar').innerHTML=['JAN','FEB','MÄR','APR','MAI','JUN','JUL','AUG','SEP','OKT','NOV','DEZ'].map((m,i)=>'<div class="month '+(E.month(state)===i?'current':'')+'" '+(E.month(state)===i?'aria-current="date"':'')+'>'+m+'</div>').join('');
    $('#stats').innerHTML=[['KONTOSTAND',money(state.cash),state.debt?money(state.debt)+' Kredit':'Schuldenfreier Betrieb','€'],['ACKERFLÄCHE',num(state.fields.reduce((a,f)=>a+f.ha,0))+' ha',state.fields.length+' eigene Schläge','▤'],['WETTER',state.weather.temp+' °C',state.weather.label+' · '+num(state.weather.rain)+' mm Regen',state.weather.rain?'☂':'☀'],['ARBEITSPLAN',state.jobs.length+' Aufträge',num(state.jobs.reduce((a,j)=>a+j.remaining,0))+' h offen · 8 h pro Tag','◷']].map(([label,value,sub,icon])=>'<div class="stat"><span class="stat-label">'+label+'</span><span class="stat-icon" aria-hidden="true">'+icon+'</span><strong class="'+(label==='KONTOSTAND'&&state.cash<0?'negative':'')+'">'+value+'</strong><small>'+sub+'</small></div>').join('');
    $('#main').innerHTML=({hof,felder,arbeit,maschinen,lager,finanzen,hilfe}[view]||hof)();
    if($('#farm-world')){
      const host=$('#farm-world'),mountedState=state;
      import('./farm3d.js?v=0.2.0').then(module=>{
        if(generation!==mapGeneration||!host.isConnected)return;
        host.querySelector('.loading-scene')?.remove();
        stopMap=module.mount(host,mountedState,selected,pickField,{onPose:pose=>{mountedState.world3d={tractor:pose};if(state===mountedState)persist();},onMessage:toast});
      }).catch(error=>{
        if(generation!==mapGeneration||!host.isConnected)return;
        host.querySelector('[data-three-status]').textContent='3D konnte nicht gestartet werden.';
        const surface=host.querySelector('.three-surface');surface.classList.add('three-error');surface.textContent='Die 3D-Ansicht benötigt WebGL 2 und einen Webserver. Öffne Ackerzeit über deinen Spiellink. Flächen, Aufträge und Spielstand bleiben über die Menüs erreichbar.';
        console.warn('Ackerzeit 3D:',error);
      });
    }
  }
  function change(){persist();render();}
  async function confirm(title,text){const dialog=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='ok'),{once:true}));}
  function download(data,name){const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  document.addEventListener('click',async event=>{
    const b=event.target.closest('button');if(!b||b.disabled)return;
    if(b.hasAttribute('data-close-field')){$('#hof-detail')?.classList.remove('is-open');return;}
    if(b.dataset.view){view=b.dataset.view;location.hash=view;render();return;}
    if(b.dataset.field){if(!['hof','felder'].includes(view))view='felder';pickField(Number(b.dataset.field));return;}
    let result=null,success='Erledigt.';
    if(b.id==='next'||b.id==='week'){const days=E.advance(state,b.id==='week'?7:1);success=days+' Spieltag'+(days!==1?'e':'')+' vergangen.';result='';}
    if(b.id==='queue'){result=E.queue(state,selected,action);success='Arbeit eingeplant. Mit dem nächsten Tag beginnt die Ausführung.';}
    if(b.dataset.cancel){result=E.cancel(state,Number(b.dataset.cancel));success='Auftrag storniert. Restliche Betriebsmittel wurden zurückgebucht.';}
    if(b.dataset.buy){result=E.buy(state,b.dataset.buy,Number($('#buy-'+b.dataset.buy).value));success='Betriebsmittel gekauft.';}
    if(b.dataset.sell){result=E.sell(state,b.dataset.sell,Number($('#sell-'+b.dataset.sell).value));success='Ernte verkauft.';}
    if(b.dataset.do){const op=b.dataset.do;if(op==='export'){stopMap?.save?.();download(JSON.stringify(state,null,2),'ackerzeit-spielstand-'+state.day+'.json');toast('Spielstand exportiert.');return;}if(op==='import'){$('#import-file').click();return;}if(op==='reset'){if(!await confirm('Neues Spiel starten?','Dein aktueller Fortschritt wird ersetzt. Ein vorheriger JSON-Export bleibt erhalten.'))return;state=E.fresh();selected=1;view='hof';persistenceBlocked=false;$('#save-warning').hidden=true;result='';success='Ein neuer Betrieb wurde gestartet.';}else{const descriptions={land:['Feld kaufen?','Du kaufst 2 ha Ackerland für 28.000 €.'],expand:['Lager erweitern?','40 t zusätzliche Kapazität kosten 6.500 €.'],loan:['Kredit aufnehmen?','Du erhältst 10.000 €. Der Zinssatz beträgt 5 % pro Jahr.'],repay:['Kredit tilgen?','10.000 € werden vom Konto abgebucht.'],maintain:['Traktor warten?','Die Wartung kostet '+money(Math.ceil((100-state.tractor.condition)*35))+'.']};if(descriptions[op]){if(!await confirm(...descriptions[op]))return;result=op==='repay'?E.loan(state,true):E[op](state);}}}
    if(result!==null){if(!result)change();toast(result||success);}
  });
  document.addEventListener('change',event=>{if(event.target.id==='field-action'){action=event.target.value;const f=state.fields.find(f=>f.id===selected);$('#action-note').innerHTML=actionInfo(f,action);$('#queue').disabled=!!E.reason(state,f,action);}});
  $('#import-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{if(file.size>2000000)throw Error();const s=JSON.parse(await file.text());if(!E.validate(s))throw Error();if(!await confirm('Spielstand laden?','Der aktuelle Fortschritt wird durch den Spielstand vom '+shortDate(s.day)+' ersetzt.'))return;state=s;selected=state.fields[0].id;persistenceBlocked=false;$('#save-warning').hidden=true;change();toast('Spielstand geladen.');}catch{toast('Ungültige oder nicht unterstützte Spielstand-Datei. Dein Fortschritt bleibt erhalten.');}});
  window.addEventListener('hashchange',()=>{const key=location.hash.slice(1);if([...pages.map(p=>p[0]),'hilfe'].includes(key)&&view!==key){view=key;render();}});
  if([...pages.map(p=>p[0]),'hilfe'].includes(location.hash.slice(1)))view=location.hash.slice(1);

  // Dispose the renderer on navigation so no background animation loops survive.
  window.addEventListener('pagehide',()=>{if(stopMap){stopMap();stopMap=null;}});
  window.addEventListener('pageshow',event=>{if(event.persisted)render();});

  render();persist();
})();
