const {chromium}=require('playwright');
const assert=require('assert/strict'),http=require('http'),fs=require('fs'),path=require('path');
const base=path.resolve(__dirname,'..');
const output=process.env.ACKERZEIT_TEST_OUTPUT||path.join(require('os').tmpdir(),'ackerzeit-browser-qa');
fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{let p=path.join(base,decodeURIComponent(req.url.split('?')[0]));if(p.endsWith('/'))p+='index.html';res.setHeader('Content-Type',({'.js':'text/javascript','.json':'application/json','.glb':'model/gltf-binary','.html':'text/html','.css':'text/css','.png':'image/png'})[path.extname(p)]||'application/octet-stream');fs.readFile(p,(e,b)=>{res.statusCode=e?404:200;res.end(e?'not found':b);});});
(async()=>{
await new Promise(r=>server.listen(8089,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader']});

const results=[];
for(const [width,height] of (process.env.ACKERZEIT_TEST_COMPACT?[[360,640]]:[[390,844],[844,390],[1365,900]])){
 console.log('Work test',width,height);
 const context=await browser.newContext({viewport:{width,height},isMobile:width<700,hasTouch:width<700});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8089');await page.waitForFunction(()=>document.querySelector('#farm-world')?.dataset.ready==='true');
 assert.equal(await page.locator('#nav [data-view=arbeit]').count(),0);
 await page.locator('.field-pill[data-field="1"]').click();
 await page.screenshot({path:path.join(output,'field-actions-'+width+'.png')});
 await page.locator('[data-start-work=cultivate]').click();
 await page.locator('[data-map=rate]').click();await page.locator('[data-map=rate]').click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')).jobs[0]?.remaining<1.8,null,{timeout:50000});
 await page.screenshot({path:path.join(output,'field-working-'+width+'.png')});
 await page.locator('[data-map=stop]').click();
 const stopped=await page.evaluate(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')));assert.equal(stopped.jobs[0].paused,true);assert.equal(stopped.day,'2026-03-01');assert.equal(stopped.fields[0].stage,'stubble');assert.ok(stopped.tractor.hours>2840);
 await page.reload();await page.waitForFunction(()=>document.querySelector('#farm-world')?.dataset.ready==='true');
 const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')));assert.equal(after.jobs[0].remaining,stopped.jobs[0].remaining);
 await page.locator('.field-pill[data-field="1"]').click();await page.locator('[data-resume-work]').click();await page.locator('[data-map=rate]').click();await page.locator('[data-map=rate]').click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')).fields[0].stage==='prepared',null,{timeout:60000});
 const complete=await page.evaluate(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')));assert.equal(complete.jobs.length,0);assert.equal(complete.workedToday,2.2);assert.equal(complete.day,'2026-03-01');assert.equal(complete.fuel,424);assert.equal(complete.tractor.hours,2842.2);
 await page.waitForFunction(()=>document.querySelector('#farm-world')?.dataset.ready==='true');
 await page.locator('.field-pill[data-field="1"]').click();assert.equal(await page.locator('[data-start-work=barley]').isEnabled(),true);
 await page.locator('[data-start-work=barley]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')).fields[0].stage==='growing',null,{timeout:60000});
 const sown=await page.evaluate(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')));assert.equal(sown.fields[0].crop,'barley');assert.ok(sown.seed.barley<2);
 await page.waitForFunction(()=>document.querySelector('#farm-world')?.dataset.ready==='true');await page.locator('#next').click();
 const day=await page.evaluate(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')));assert.equal(day.day,'2026-03-02');assert.equal(day.workedToday,0);
 await page.waitForFunction(()=>document.querySelector('#farm-world')?.dataset.ready==='true');
 await page.locator('.field-pill[data-field="1"]').click();
 await page.locator('[data-start-work=fertilize]').click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')).fields[0].fertilized,null,{timeout:60000});
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('ackerzeit-save-v1'));s.day='2026-07-15';s.workedToday=0;s.weather={temp:20,rain:0,label:'Heiter'};s.fields[0].stage='ready';s.fields[0].heat=1200;s.fields[0].moisture=50;localStorage.setItem('ackerzeit-save-v1',JSON.stringify(s));});
 await page.reload();await page.waitForFunction(()=>document.querySelector('#farm-world')?.dataset.ready==='true');
 await page.locator('.field-pill[data-field="1"]').click();await page.locator('[data-start-work=harvest]').click();
 await page.locator('[data-map=rate]').click();await page.locator('[data-map=rate]').click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')).jobs[0]?.remaining<.65,null,{timeout:50000});
 await page.screenshot({path:path.join(output,'field-harvest-'+width+'.png')});
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')).fields[0].stage==='stubble',null,{timeout:60000});
 const harvested=await page.evaluate(()=>JSON.parse(localStorage.getItem('ackerzeit-save-v1')));assert.ok(harvested.stock.barley>0);assert.equal(harvested.jobs.length,0);
 const b=await page.evaluate(()=>({w:innerWidth,h:innerHeight,x:document.documentElement.scrollWidth,y:document.documentElement.scrollHeight}));assert.ok(b.x<=b.w&&b.y<=b.h);assert.deepEqual(errors,[]);
 results.push({viewport:width+'x'+height,dispatch:true,visibleWork:true,pauseReloadResume:true,cultivate:true,sow:true,fertilize:true,harvest:true,dayChange:true,errors});await context.close();
}
fs.writeFileSync(path.join(output,'live-work-browser-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
